[package]
name = "anathema-widget-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anathema-render = { path = "../anathema-render" }
bitflags = { workspace = true }
unicode-width = { workspace = true }
thiserror = { workspace = true }
parking_lot = "0.12.1"

