[package]
name = "anathema"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"
license = "MIT"
description = "Text User Interface library (TUI) with a template language and runtime"
documentation = "https://togglebyte.github.io/anathema-guide/"
homepage = "https://github.com/togglebyte/anathema"
repository = "https://github.com/togglebyte/anathema"

[features]
default = ["runtime"]
widgets = ["dep:widgets", "antstring"]
templates = ["dep:templates", "widgets"]
runtime = ["dep:runtime", "templates"]
logging = [
    "display/logging",
    "runtime/logging",
    "templates/logging",
    "widgets/logging",
]
serde-json = [
    "widgets/serde-json",
    "runtime/serde-json",
]

[dependencies]
antstring = { path = "antstring", optional = true, version = "0.1.0" }
display = { path = "display", version = "0.1.0" }
runtime = { path = "runtime", optional = true, version = "0.1.0" }
templates = { path = "templates", optional = true, version = "0.1.0" }
widgets = { path = "widgets", optional = true, version = "0.1.0" }
