[package]
name = "anathema"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "Create beautiful, easily customisable terminal applications"
keywords = ["tui", "terminal", "widgets", "ui"]
categories = ["command-line-interface", "tui", "terminal", "template", "markup"]
readme = "./README.md"
documentation = "https://docs.rs/anathema"
homepage = "https://github.com/togglebyte/anathema"
repository = "https://github.com/togglebyte/anathema"

[dependencies]
anathema-compiler = { path = "./anathema-compiler" }
anathema-render = { path = "./anathema-render" }
anathema-runtime = { path = "./anathema-runtime" }
anathema-values = { path = "./anathema-values" }
anathema-vm = { path = "./anathema-vm" }
anathema-widget-core = { path = "./anathema-widget-core" }
anathema-widgets = { path = "./anathema-widgets" }
anathema-value-derive = { path = "./anathema-value-derive" }

[lints]
workspace = true

[workspace.dependencies]
bitflags = "2.4.1"
crossterm = "0.27.0"
unicode-width = "0.1.11"
thiserror = "1.0.56"
parking_lot = "0.12.1"
kempt = "0.2.3"

[workspace]
members = [
    "anathema-compiler",
    "anathema-render",
    "anathema-runtime",
    "anathema-values",
    "anathema-vm",
    "anathema-widget-core",
    "anathema-widgets",
    "anathema-value-derive",
]

[workspace.lints.rust]
unsafe_code = "forbid"
rust_2018_idioms = "deny"

[workspace.lints.clippy]
from_over_into = "allow"
len_without_is_empty = "allow"
new_without_default = "allow"
should_implement_trait = "allow"
