[package]
name = "anathema-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anathema-widgets = { path = "../anathema-widgets" }
anathema-render = { path = "../anathema-render" }
