[package]
name = "display"
version = "0.1.0"
edition = "2021"

[features]
default = []
events = []
logging = ["log"]

[dependencies]
bitflags = "1.3.2"
crossterm = "0.23.2"
log = { version = "0.4.17", optional = true }
unicode-width = "0.1.9"
