[package]
name = "templates"
version = "0.1.0"
edition = "2021"

[features]
default = []
logging = ["log"]

[dependencies]
display = { version = "0.1.0", path = "../display" }
log = { version = "0.4.17", optional = true }
widgets = { version = "0.1.0", path = "../widgets" }
